"""
Auto-generate YOLO bounding box labels for collected real-world images.

Uses the existing model to detect hand position. If the model misses a frame,
falls back to a default centre-box covering 65% of the frame.

Usage:
    .venv\Scripts\python.exe scripts\auto_label.py

Input:  dataset/real/images/<gesture>/*.jpg
Output: dataset/real/labels/<gesture>/*.txt  (YOLO format)
Also writes: dataset/real/data.yaml
"""
import cv2
import os
import sys
sys.path.insert(0, ".")
from src.detector import GestureDetector, CLASS_NAMES

MODEL = "models/gesture.onnx"
IMAGE_BASE = os.path.join("dataset", "real", "images")
LABEL_BASE = os.path.join("dataset", "real", "labels")

# Low thresholds — we only need the box position, not high confidence
detector = GestureDetector(MODEL, conf_threshold=0.15, min_hand_pct=0.5, max_hand_pct=95.0)


def default_box(w, h, margin=0.15):
    """Centre box covering (1 - 2*margin) of the frame."""
    x1 = int(w * margin)
    y1 = int(h * margin)
    x2 = int(w * (1 - margin))
    y2 = int(h * (1 - margin))
    return x1, y1, x2, y2


def to_yolo(box, w, h):
    x1, y1, x2, y2 = box
    x_c = ((x1 + x2) / 2) / w
    y_c = ((y1 + y2) / 2) / h
    bw  = (x2 - x1) / w
    bh  = (y2 - y1) / h
    return x_c, y_c, bw, bh


def main():
    total_auto = total_fallback = total_images = 0

    for gesture in CLASS_NAMES:
        img_dir = os.path.join(IMAGE_BASE, gesture)
        if not os.path.isdir(img_dir):
            continue

        lbl_dir = os.path.join(LABEL_BASE, gesture)
        os.makedirs(lbl_dir, exist_ok=True)

        class_id = CLASS_NAMES.index(gesture)
        images = sorted(f for f in os.listdir(img_dir) if f.lower().endswith((".jpg", ".png")))

        auto = fallback = 0
        for fname in images:
            img_path = os.path.join(img_dir, fname)
            img = cv2.imread(img_path)
            if img is None:
                continue
            h, w = img.shape[:2]

            dets = detector.detect(img)
            if dets:
                top = max(dets, key=lambda d: d.confidence)
                box = top.box
                auto += 1
            else:
                box = default_box(w, h)
                fallback += 1

            x_c, y_c, bw, bh = to_yolo(box, w, h)
            lbl_path = os.path.join(lbl_dir, os.path.splitext(fname)[0] + ".txt")
            with open(lbl_path, "w") as f:
                # class_id is always the gesture being collected — not the model's guess
                f.write(f"{class_id} {x_c:.6f} {y_c:.6f} {bw:.6f} {bh:.6f}\n")

        total_auto     += auto
        total_fallback += fallback
        total_images   += len(images)
        print(f"  {gesture:<14} {len(images):>4} images  —  "
              f"{auto} model-box  /  {fallback} default-box")

    print()
    print(f"Total: {total_images} images  ({total_auto} auto-labeled, {total_fallback} default-box)")

    # Write data.yaml for retraining
    yaml_path = os.path.join("dataset", "real", "data.yaml")
    yaml_lines = [
        "path: dataset/real",
        "train: images",
        "val:   images",
        "",
        f"nc: {len(CLASS_NAMES)}",
        f"names: {CLASS_NAMES}",
        "",
        "# Generated by scripts/auto_label.py",
        "# For a proper train/val split run scripts/split_dataset.py on dataset/real",
    ]
    with open(yaml_path, "w") as f:
        f.write("\n".join(yaml_lines) + "\n")

    print(f"Wrote {yaml_path}")
    print()
    print("Next step — upload dataset/real/ to Google Colab and retrain:")
    print("  from ultralytics import YOLO")
    print("  model = YOLO('yolov8n.pt')")
    print("  model.train(data='dataset/real/data.yaml', epochs=50, imgsz=640, batch=16)")
    print("  model.export(format='onnx')")


if __name__ == "__main__":
    main()
